*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZBC_RESET_PWDU01.
                    "TABLEFRAME_ZBC_RESET_PWD
INCLUDE LZBC_RESET_PWDU02.
                    "TABLEPROC_ZBC_RESET_PWD